### ISSUE TITLE
git-deps fails to work with Flask >= 2.2 (safe_join has been removed in Flask)

### ISSUE THREAD

**Issue by zorun** [aspiers/git-deps#110]
I installed git-deps via pip, and it fails to start in server mode:

```
$ git deps -s
Cannot find flask module which is required for webserver mode.
```

After some debugging, it turns out that the `safe_join` import fails because that function has just been removed from Flask: https://github.com/pallets/flask/issues/4516

Since git-deps does not pin constrain the dependency on flask, it pulls the latest available version.

The workaround I'm using for now is:
```
$ pip install 'flask<2.1'
```

**Comment by imwcc** [comment]
I meet a same issue

**Comment by titarch** [comment]
I ran into this issue but downgrading flask was not enough. I also had to downgrade Werkzeug:
`pip install Werkzeug==2.2.2`
