### ISSUE TITLE
server not working: 404 request to cola.v3.min.js

### ISSUE THREAD

**Issue by paulwellnerbou** [aspiers/git-deps#49]
Setting up a git-deps server on a clean ubuntu 15.04 system (in a docker image) results in 404 requests trying to get /node_modules/webcola/WebCola/cola.v3.min.js, although /node_modules/webcola/WebCola/cola.min.js exists.

I worked around this issue in https://github.com/paulwellnerbou/git-deps-docker creating a symlink when building the docker image:

```RUN ln -s /git-deps/html/node_modules/webcola/WebCola/cola.min.js /git-deps/html/node_modules/webcola/WebCola/cola.v3.min.js```

Maybe its the node/npm version doing different naming than expected?

**Comment by aspiers** [comment]
Upstream broke it :-(  I've submitted [an issue](https://github.com/tgdwyer/WebCola/issues/100) and [a fix](https://github.com/tgdwyer/WebCola/pull/101).
