### ISSUE TITLE
need proper installation mechanism

### ISSUE THREAD

**Issue by aspiers** [aspiers/git-deps#51]
Currently it's expected that `git-deps` will be run from the top of the git repo (see #27 and #22), and this only works by following the installation instructions which say to do:

```
ln -s /path/to/git-deps/repo/git-deps ~/bin
```

However that's a really lame installation process, which also assumes that the files under `html/` will be retrieved from relative to the `git-deps` scripts.  Instead it should be parametrized to facilitate clean packaging.  @bmwiedemann has already written a Makefile in https://build.opensuse.org/package/show/home:bmwiedemann/git-deps which supports the usual `$DESTDIR` and `$PREFIX` variables, although maybe we should go the Pythonic route and write a `setup.py` instead - I'm not sure.

**Comment by aspiers** [comment]
I have converted it into a Python module - currently in the `module` branch but will release to PyPi soon-ish.

**Comment by nicolasbock** [comment]
@aspiers Would you mind tagging a release? I am packaging it for gentoo, and a release would help.

**Comment by aspiers** [comment]
@nicolasbock Will do but I still have a bit of work left to do before the conversion to a module is complete.  Perhaps you could help me test it?  By now the only problem I know about is that click and drag doesn't work in the visualization.

**Comment by nicolasbock** [comment]
I have it installed now without the graphical UI. I will install the dependencies today so that I can play around with it more.

**Comment by aspiers** [comment]
It's finally hackweek so I'm revisiting this now, and being reminded how much Python's ecosystem miserably *sucks* :angry:

**Comment by aspiers** [comment]
This is now done: https://pypi.org/project/git-deps/

There will no doubt be a few teething problems.  For instance it seems that `gitfile-handler.desktop` is not being installed correctly yet.  But I'll open a separate issue for that.
