### ISSUE TITLE
git-deps incompatible with pygit2 version >= 0.22.1 (with patch)

### ISSUE THREAD

**Issue by mstefani** [aspiers/git-deps#57]
pygit2 incompatibly changed the API for the Diff interface in version 0.22.1 .
The attached small (4 changed lines) 
[0001-Account-for-Diff-API-changes-in-pygit2-version-0.22.txt](https://github.com/aspiers/git-deps/files/108060/0001-Account-for-Diff-API-changes-in-pygit2-version-0.22.txt)
patch fixes it for me (Fedora 23 with pygit2 version 0.23.0).
Of course this patch breaks git-deps for older pygit2 versions.

**Comment by aspiers** [comment]
Thanks!  Please could you submit a pull request for this?  Ideally it could automatically detect which API is available and adjust behaviour accordingly?

**Comment by Valodim** [comment]
Nothing happened in a while so I took the liberty to submit this patch as a PR, see #58

**Comment by aspiers** [comment]
I merged #58 so this can be closed now.
