### ISSUE TITLE
[meta] commits not associated with author's github account

### ISSUE THREAD

**Issue by waldyrious** [aspiers/git-deps#64]
The list of commits in https://github.com/aspiers/git-deps/commits shows that most of the commits are not associated to a github account (which should be @aspiers), and that makes the [graphs](https://github.com/aspiers/git-deps/graphs) much less useful/accurate.

The graphs are not just a neat visualization -- they also help potential contributors to assess the pace and stability of activity in the project (a project that appears to be stale may discourage contributor involvement, for instance).

IIRC it is possible to add additional email addresses to a github account, even privately, which would fix this.

**Comment by aspiers** [comment]
Good spot, thanks a lot!  I wasn't aware of that issue.  Fixed now.  This relates to my habit of using many different prefixes of my `@adamspiers.org` domain to help filter email accurately (and track where spam comes from).  I guess this means now I need to go through all my github projects and add email addresses to my account wherever relevant ... Again, thanks a lot for the heads up!

**Comment by waldyrious** [comment]
Happy to help, and sorry for triggering extra work! 😇
