### ISSUE TITLE
JS error - 'noty.js:2345 Uncaught TypeError: Cannot call a class as a function(…)'

### ISSUE THREAD

**Issue by matrix-amiel** [aspiers/git-deps#65]
Hi.
I would like to working with your cool feature but I've receive js error when I click on submit -
 'noty.js:2345 Uncaught TypeError: Cannot call a class as a function(…)' 
![image](https://user-images.githubusercontent.com/17809866/31067125-ed4cfcac-a759-11e7-9ae8-543871c6cff7.png)
Do you know why? could you help me?
Thanks
Amiel

**Comment by aspiers** [comment]
I'm not sure why this is happening, sorry.  What was the exact installation procedure you used?
