### ISSUE TITLE
git deps cannot be stopped with CTRL-C

### ISSUE THREAD

**Issue by mstefani** [aspiers/git-deps#83]
This is kinda a follow up to issue #82.
I tried to stop 'git deps commit' with CTRL-C but that doesn't works. I had to kill the 'python git-deps' process.

**Comment by mstefani** [comment]
A simple reproducer:
git clone git://source.winehq.org/git/wine.git
git deps 186d107e4d586860008e2ac5fb1e2ebdbce06145
186d107e4d586860008e2ac5fb1e2ebdbce06145 50e53643300da159a7680fb862a4f4c747a12697
263f6ef20123bd35dbcecca48a3137dc2be9ef94 282eb73bc3eafe63f3f33117370b7e891011353b
263f6ef20123bd35dbcecca48a3137dc2be9ef94 b80101eb6516e0ac778c1d61bbb26a032ccbd0a2
263f6ef20123bd35dbcecca48a3137dc2be9ef94 d5a478edfa98164665d83ba6989aca499910752f
263f6ef20123bd35dbcecca48a3137dc2be9ef94 1522282673e19f6cb31b775bafd8cb564e05d138
^C^C^C^C^Ccf22c2c16c50707b85b6700721ca146dd376b01a f3346a789ea01e578b93c7d4f0fdf870f80b446d
cf22c2c16c50707b85b6700721ca146dd376b01a a4d0abb2344f93552add6eef9a723573c76ba6a2
cf22c2c16c50707b85b6700721ca146dd376b01a b995ed00a742494dc68ed829afd51f052bada4d3
6fb0c79022323a820d122943745f9aa60a346aa0 f3346a789ea01e578b93c7d4f0fdf870f80b446d
6fb0c79022323a820d122943745f9aa60a346aa0 728bf77c83e331d821272131aaf8eb71600c2a77
6fb0c79022323a820d122943745f9aa60a346aa0 b995ed00a742494dc68ed829afd51f052bada4d3

**Comment by midenok** [comment]
Please [fix](http://zguide.zeromq.org/py:interrupt) this trivial and nasty bug ASAP!

**Comment by aspiers** [comment]
Hopefully #94 will work.  Can someone else volunteer to test it?

**Comment by aspiers** [comment]
Sorry this took so long to fix :-(
