### ISSUE TITLE
updating INSTALL.md for python 3

### ISSUE THREAD

**Issue by nickdesaulniers** [aspiers/git-deps#98]
I was having a rough time installing git-deps based on the instructions provided.  Eventually:

```sh
$ pip3 install pygit2 git-deps
$ echo "$HOME/.local/bin" >> .zshrc
```
worked for me.  Maybe it's more obvious to more frequent python users, but took me some time to figure out.

**Comment by aspiers** [comment]
In general this project needs to be tested much more carefully on Python 3, given that 2.7 is EOL.
